# Generated by Django 2.2.3 on 2019-07-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190727_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideia',
            old_name='categorias_outros',
            new_name='categoria_outros',
        ),
    ]
